title: test_mathjax
lang: en
description: Get math to work

remote_theme: mmistakes/minimal-mistakes
readme_index:
  with_frontmatter: true

exclude:
  - Gemfile

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
